(#117) Refatoração das requisições na api
fga-eps-mds/2022.2-Amis-Front pull request #15
Opened 2023-01-27 05:14 UTC by gabrielapivetta

# Descrição

Refatoração / reorganização das requisições na api, dentro da pasta service.

# Mudanças

* Criação da pasta service com as chamadas de rotas na api
* Estilização das telas de turmas e alunas
* Melhorias no fluxo de turmas, alunas, matrícula e assistentes
* Adição de toasts de feedback de ações para o usuário

# Screenshots
![Screenshot from 2023-01-27 02-11-58](https://user-images.githubusercontent.com/65376200/215014286-daed6bb7-458b-4fbe-b6eb-09e91993f1de.png)
![Screenshot from 2023-01-27 02-11-33](https://user-images.githubusercontent.com/65376200/215014292-06fa7faf-8d28-41af-967f-42a89f2b59b9.png)
![Screenshot from 2023-01-27 02-11-26](https://user-images.githubusercontent.com/65376200/215014297-64bc6236-513e-4d3d-bdb6-03137a5f381d.png)
![Screenshot from 2023-01-27 02-10-26](https://user-images.githubusercontent.com/65376200/215014301-382b2fc5-796d-44ca-a352-d397652f820e.png)

2023-01-30 13:49 UTC, jps12 requested changes
Acho que a sua branch é meio antiga e possui apenas os testes da página de turmas confere? Acho que seria bom pegar os testes da dev só por garantia mesmo. Tirando isso apenas o arquivo api que não foi encontrado

2023-01-30 13:49 UTC, jps12 commented on src/services/turmas.tsx
> +import api from "./api";
Esse arquivo ./api não existe, não achei ele aqui. Isso ta quebrando a aplicação

2023-01-31 00:48 UTC, gabrielapivetta commented on src/services/turmas.tsx
> +import api from "./api";
O arquivo estava incluso em outro PR já aceito.

2023-01-31 01:07 UTC, merged

2023-01-31 01:07 UTC, KalebeLopes commented
Ajustes sugeridos pelo @jps12 foram realizados. 
Ótimo trabalho!